### ISSUE TITLE
Collaboration 

### ISSUE THREAD

**Issue by yashu2001** [imabp/Collabs#1]
# Chef's Hack
## brainstormed ideas into amazing projects under the guidance of a mentor.

Do let me know about your ideas and what your community does.

CodeChef SRM is a non-profit technical student's chapter under the alliance of CodeChef, a product of Unacademy. Our main motive is to spread and promote competitive coding on our campus. It is a group of people brought together in order to gain knowledge and learn new skills. We organize various events like Coding and Debugging competition to give students the correct exposure required to become better programmers. The workshops we conduct have renown speakers to provide the best learning environment to the students.

## Event Date (Can be tentative)

Chef's Hack will officially commence from 23/24 October 2020 and will continue till 9 November 2020.

## Time ( Timezone)

IST

## Expected Attendance

We would be needing you to mentor students to get started with ideation(1 day)
Suggest improvements  after ideation(1 day)
Mentor students during the hackathon and reviewing their projects(5/6 days (Not the whole day obviously :P))

**Students**

- We want students to understand how projects are taken from ideation to development unlike other hackathons because our aim is to nurture future software engineers, not just coders.

**Comment by imabp** [comment]
@yashu2001 I saw the details. But due to my fixed schedules and university work, I cannot mentor up the things. 

But I can have a speak up event on open source for your community. 

Let me know in this thread, if that sounds good : )

**Comment by yashu2001** [comment]
Hey Abir thanks for your reply, I'll let you know if there are any open dates for speakers.

**Comment by imabp** [comment]
Sure brother. :) Will be looking forward to it

**Comment by imabp** [comment]
@yashu2001 Closing this issue, if no confirmation about speaker.

**Comment by yashu2001** [comment]
Hey I'm really sorry for the delay, my exams are going on.

Unfortunately our team has decided that we will not take any student speakers.However we look forward to future collaboration thanks.

Apologies for delayed response.

**Comment by imabp** [comment]
Sure its all fine. : )
