### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by iamgunjan** [imabp/Collabs#2]
# Event Name
Workshop on Open-Source and GSSOC

### Community Name /  Name / Host Information
GirlScript Summer of Code / Gunjan Paneri 

## Quick Description
Host info: Student at Chandigarh University. I am selected as campus ambassador in Girlscript Summer of Code 

Do let me know about your ideas and what your community does.
GirlScript Summer of Code is the 3 month long Open Source program during summers conducted by GirlScript Foundation, started in 2018, with an aim to help beginners get started with Open Source Development while encouraging diversity.

## Event Date (Can be tentative)
20 February ,2021

I would be glad if you let me know the possible event date, dont mind, just rough idea if you haven't fixed it yet. We can discuss the date later on in the thread

## Time ( Timezone)
around 7 or 8 pm

Most of the times, I am free during evening . 
We can have a talk no worries. 

## Expected Attendance
Like its a small workshop for basics I guess there will be a strength around 30-50 or more students, I'll try my best to spread as much as I can will be greatful if you also help in promoting

**Students**
I asure you there will be almost 80% of the students from colleges and universities

- [ ] I really want that open source should impact more amount of students, at least *15+ students* must be present in the event

**Industries**
Most of the students will be from Chandigarh University

- [ ] If you are having special audience like industry people or a small group of software engineers, then no issues, we can have the event too

**Comment by imabp** [comment]
Thank you for it. 
But I am a bit occupied with some sponsored events, from MLH and Postman. 
Will surely meet you guys up at Girlscript Summer of Code.
